include:
  - path: ../../common/prometheus.compose.yml
  - path: ../../common/grafana.compose.yml

# Auto Update containers when new version is available
services:
  watchtower:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    image: containrrr/watchtower
    # healthcheck already done by container `/watchtower --health-check`
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_DEBUG: 'true'
      WATCHTOWER_LOG_FORMAT: json
      WATCHTOWER_POLL_INTERVAL: 300 # seconds => 5 minutes
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN:?WATCHTOWER_HTTP_API_TOKEN not set}
      WATCHTOWER_HTTP_API_METRICS: 'true'
      REPO_USER: d3strukt0r
      REPO_PASS: ${REPO_PASS:?REPO_PASS not set}
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.watchtower
