# Auto Update containers when new version is available
services:
  watchtower:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    image: containrrr/watchtower
    # TODO: How do we check?
    #healthcheck:
      #test: curl --fail http://localhost || exit 1
      #test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Zurich
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_LOG_FORMAT: json
      WATCHTOWER_POLL_INTERVAL: 300 # seconds => 5 minutes
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.watchtower
