services:
  pwa:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: d3strukt0r/weleda-webcenter-text-export
    init: false
    deploy:
      resources:
        limits:
          memory: 160M
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
    networks:
      - default
      - traefik_proxy
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.pwa
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`webcenter-text-export.manuele-vaccari.ch`) || Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
