services:
  mariadb:
    volumes:
      - ./database:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
  redis:
    volumes:
      - ./redis:/data
  minio:
    volumes:
      - ./minio:/data

