include:
  - path: ../../common/mariadb.compose.yml
    env_file: .mariadb.env
  - path: ../../common/phpmyadmin.compose.yml
    env_file: .phpmyadmin.env

services:
  web-phpfpm:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    image: d3strukt0r/arepazo:phpfpm-develop
    init: false
    deploy:
      resources:
        limits:
          memory: 280M
    healthcheck:
      # TODO: Figure out why i'm getting
      # web-phpfpm-1  | NOTICE: Access to the script '/status' has been denied (see security.limit_extensions)
      # web-phpfpm-1  | 127.0.0.1 -  21/Jun/2024:11:52:35 +0000 "GET /status" 403
      #test: php-fpm-healthcheck || exit 1
      start_period: 20s
    depends_on:
      - mariadb
    volumes:
      - ./uploads:/usr/local/src/app/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: db
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:?WORDPRESS_DB_PASSWORD not set}
      WORDPRESS_DB_NAME: db

      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY:?WORDPRESS_AUTH_KEY not set}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY:?WORDPRESS_SECURE_AUTH_KEY not set}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY:?WORDPRESS_LOGGED_IN_KEY not set}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY:?WORDPRESS_NONCE_KEY not set}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT:?WORDPRESS_AUTH_SALT not set}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT:?WORDPRESS_SECURE_AUTH_SALT not set}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT:?WORDPRESS_LOGGED_IN_SALT not set}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT:?WORDPRESS_NONCE_SALT not set}
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.web-phpfpm

  web-nginx:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    image: d3strukt0r/arepazo:nginx-develop
    init: false
    deploy:
      resources:
        limits:
          memory: 160M
    healthcheck:
      # TODO: Change check, get 302 from fpm
      # web-phpfpm-1  | 192.168.208.5 -  21/Jun/2024:12:25:16 +0000 "GET /index.php" 302
      # web-nginx-1   | 127.0.0.1 - - [21/Jun/2024:12:25:16 +0000] "GET / HTTP/1.1" 302 5 "-" "curl/7.88.1" "-" "-"
      #test: curl --fail http://localhost:8080 || exit 1
      start_period: 30s
    networks:
      - default
      - traefik_proxy
    depends_on:
      - web-phpfpm
    volumes:
      - ./uploads:/usr/local/src/app/wp-content/uploads:ro
    environment:
      UPSTREAM_SERVER: web-phpfpm:9000
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.web-nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`arepazo.ch`) || Host(`www.arepazo.ch`) || Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
