# https://github.com/elastic/elasticsearch/blob/8.10/docs/reference/setup/install/docker/docker-compose.yml
services:
  # Test with:
  # docker run --rm --log-driver=fluentd --log-opt tag="myapp.test" ubuntu echo '{"key":"value"}'
  # docker run --rm --log-driver=fluentd --log-opt tag="myapp.web" -p 8082:80 nginx
  fluentd:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/log
    ports:
      - '24224:24224'
    environment:
      DATABASE_URL: mongodb://${DATABASE_USER:?error}:${DATABASE_PASSWORD:?error}@mongo:27017/fluentd

  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USER:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?error}

  mongo-express:
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 120M
    networks:
      - default
      - traefik_proxy
    environment:
      # To avoid error "Command listDatabases requires authentication"
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DATABASE_ROOT_USER:?error}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DATABASE_ROOT_PASSWORD:?error}

      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.services.fluentd-mongo-express.loadbalancer.server.port: 8081
      traefik.http.routers.fluentd-mongo-express.entrypoints: websecure
      traefik.http.routers.fluentd-mongo-express.rule: Host(`db-logs.d3strukt0r.dev`)
      traefik.http.routers.fluentd-mongo-express.tls: true
      traefik.http.routers.fluentd-mongo-express.tls.certresolver: le

networks:
  traefik_proxy:
    external: true
