include:
  - path: ../../common/mongo.compose.yml
    env_file: .mongo.env
  - path: ../../common/mongo-express.compose.yml
    env_file: .mongo-express.env

# https://github.com/elastic/elasticsearch/blob/8.10/docs/reference/setup/install/docker/docker-compose.yml
services:
  # Test with:
  # docker run --rm --log-driver=fluentd --log-opt tag="myapp.test" ubuntu echo '{"key":"value"}'
  # docker run --rm --log-driver=fluentd --log-opt tag="myapp.web" -p 8082:80 nginx
  fluentd:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
    # TODO: How to handle this?
    #healthcheck:
    #  test: curl --fail http://localhost || exit 1
    #  test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/log
    ports:
      - '24224:24224'
    environment:
      DATABASE_URL: mongodb://${DATABASE_USER:?DATABASE_USER not set}:${DATABASE_PASSWORD:?DATABASE_PASSWORD not set}@mongo:27017/fluentd

networks:
  traefik_proxy:
    external: true
