FROM phpmyadmin

# https://forums.docker.com/t/using-docker-in-a-dockerized-jenkins-container/322/10
# https://stackoverflow.com/questions/22135897/access-docker-socket-within-container/33183227#33183227
# https://docs.docker.com/engine/api/v1.45/
