services:
  nginx:
    image: nginx
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    networks:
      - traefik_proxy
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    logging:
      driver: fluentd
      options:
        tag: ping.nginx
    labels:
      traefik.enable: true
      traefik.http.routers.ping.entrypoints: websecure
      traefik.http.routers.ping.rule: Host(`ping.d3strukt0r.dev`)
      traefik.http.routers.ping.tls: true
      traefik.http.routers.ping.tls.certresolver: le

networks:
  traefik_proxy:
    external: true
