include:
  - path: ../../../common/mariadb.compose.yml
    env_file: .mariadb.env
  - path: ../../../common/phpmyadmin.compose.yml
    env_file: .phpmyadmin.env
  - path: ../../../common/minio.compose.yml
    env_file: .minio.env

services:
  pwa:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: d3strukt0r/wedding-manuele-robine:pwa-develop
    deploy:
      resources:
        limits:
          memory: 160M
    healthcheck:
      test: curl --fail http://localhost || exit 1
      start_period: 30s
    environment:
      API_URL: http://api
      VITE_PUBLIC_API_URL: https://api-wedding-manuele-robine-dev.d3strukt0r.dev
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY:?VITE_GOOGLE_MAPS_API_KEY not set}
    networks:
      - default
      - traefik_proxy
    depends_on:
      - api
    logging:
      driver: fluentd
      options:
        # TODO: Use "${COMPOSE_PROJECT_NAME}" if we can remove "-dev" from the string
        tag: wedding-manuele-robine.dev.pwa
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pwa.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pwa.rule=Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pwa.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pwa.tls.certresolver=le

  api:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: d3strukt0r/wedding-manuele-robine:api-develop
    deploy:
      resources:
        limits:
          memory: 300M
    healthcheck:
      # TODO: Find out why `php-fpm-healthcheck` doesn't work
      #test: php-fpm-healthcheck && curl --fail http://localhost/ping || exit 1
      test: curl --fail http://localhost/ping || exit 1
      start_period: 20s
    volumes:
      - ./sessions:/var/cache/sessions
      - ./jwt:/usr/local/src/app/config/jwt:ro
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://db:${DB_PASSWORD}@mariadb:3306/db?serverVersion=10.11.2-MariaDB&charset=utf8mb4
      APP_URL: https://api-${COMPOSE_PROJECT_NAME}.d3strukt0r.dev
      TRUSTED_PROXIES: 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      CLEAR_SESSIONS_IN: /var/cache/sessions/prod
      CORS_ALLOW_ORIGIN: ^https?://(wedding-manuele-robine-dev\.d3strukt0r\.dev|localhost|127\.0\.0\.1)(:[0-9]+)?$
      JWT_PASSPHRASE: ${JWT_PASSPHRASE:?JWT_PASSPHRASE not set}
      DEFAULT_STORAGE_SOURCE: default.storage.aws
      S3_STORAGE_KEY: minio
      S3_STORAGE_SECRET: ${MINIO_PASSWORD:?MINIO_PASSWORD not set}
    networks:
      - default
      - traefik_proxy
    depends_on:
      - mariadb
    logging:
      driver: fluentd
      options:
        # TODO: Use "${COMPOSE_PROJECT_NAME}" if we can remove "-dev" from the string
        tag: wedding-manuele-robine.dev.api
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.rule=Host(`api-${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.tls.certresolver=le

  # https://stackoverflow.com/questions/76401435/why-i-cant-get-access-to-minio-console-from-docker-container
  minio-setup:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: minio/mc:latest
    restart: 'no'
    environment:
      MC_HOST_minio: http://minio:${MINIO_PASSWORD:?MINIO_PASSWORD not set}@minio:9000
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc mb minio/default
        #mc anonymous set download minio/default/public
        #mc anonymous links minio/default --recursive

networks:
  traefik_proxy:
    external: true
