services:
  pwa:
    image: d3strukt0r/wedding-manager:pwa-develop
    pull_policy: always
    init: true
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 160M
    environment:
      API_URL: http://api
      PUBLIC_API_URL: https://api-wedding-manuele-robine.d3strukt0r.dev
    networks:
      - default
      - traefik_proxy
    depends_on:
      - api
    logging:
      driver: fluentd
      options:
        tag: wedding-manuele-robine.pwa
    labels:
      traefik.enable: true

      traefik.http.routers.wedding-manuele-robine0.entrypoints: web
      traefik.http.routers.wedding-manuele-robine0.rule: Host(`manuele-robine.wedding`) || Host(`www.manuele-robine.wedding`) || Host(`eleunam-enibor.wedding`) || Host(`www.eleunam-enibor.wedding`) || Host(`wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine0.middlewares: to_https

      traefik.http.routers.wedding-manuele-robine.entrypoints: websecure
      traefik.http.routers.wedding-manuele-robine.rule: Host(`manuele-robine.wedding`) || Host(`www.manuele-robine.wedding`) || Host(`eleunam-enibor.wedding`) || Host(`www.eleunam-enibor.wedding`) || Host(`wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine.tls: true
      traefik.http.routers.wedding-manuele-robine.tls.certresolver: le

  api:
    image: d3strukt0r/wedding-manager:api-develop
    pull_policy: always
    init: true
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 240M
    volumes:
      - ./sessions:/var/cache/sessions
      - ./jwt:/usr/local/src/app/config/jwt:ro
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://db:${DB_PASSWORD}@db:3306/db?serverVersion=10.11.2-MariaDB&charset=utf8mb4
      APP_URL: https://api.manuele-robine.wedding
      TRUSTED_PROXIES: 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      CLEAR_SESSIONS_IN: /var/cache/sessions/prod
      CORS_ALLOW_ORIGIN: ^https?://(wedding-manuele-robine\.d3strukt0r\.dev|(?:www\.)?manuele-robine\.wedding|localhost|127\.0\.0\.1)(:[0-9]+)?$
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    networks:
      - default
      - traefik_proxy
    depends_on:
      - db
    logging:
      driver: fluentd
      options:
        tag: wedding-manuele-robine.api
    labels:
      traefik.enable: true

      traefik.http.routers.wedding-manuele-robine-api0.entrypoints: web
      traefik.http.routers.wedding-manuele-robine-api0.rule: Host(`api.manuele-robine.wedding`) || Host(`api.eleunam-enibor.wedding`) || Host(`api-wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine-api0.middlewares: to_https

      traefik.http.routers.wedding-manuele-robine-api.entrypoints: websecure
      traefik.http.routers.wedding-manuele-robine-api.rule: Host(`api.manuele-robine.wedding`) || Host(`api.eleunam-enibor.wedding`) || Host(`api-wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine-api.tls: true
      traefik.http.routers.wedding-manuele-robine-api.tls.certresolver: le

  db:
    image: mariadb
    pull_policy: always
    init: true
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--user=db", "--password=${DB_PASSWORD}"]
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # Create "db" user with password ${DB_PASSWORD} if it doesn't exist
      MARIADB_USER: db
      MARIADB_PASSWORD: ${DB_PASSWORD}
      # Create database "db" if it doesn't exist
      MARIADB_DATABASE: db
    networks:
      - default
    logging:
      driver: fluentd
      options:
        tag: wedding-manuele-robine.mariadb

  # Manually create PMA db and user:
  # $ mariadb --password=${MARIADB_ROOT_PASSWORD}
  # $ CREATE DATABASE phpmyadmin; GRANT ALL PRIVILEGES ON phpmyadmin.* TO 'pma'@'%' IDENTIFIED BY '${DB_PMA_PASSWORD}';
  # Then create tables from UI (In container /var/www/html/sql/create_tables.sql)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    pull_policy: always
    init: true
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    environment:
      # Default user to be logged in
      #PMA_USER: db
      #PMA_PASSWORD: ${DB_PASSWORD}
      # PhpMyAdmin User to manage PMA db
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: pma
      PMA_CONTROLPASS: ${DB_PMA_PASSWORD}
      # Other settings
      UPLOAD_LIMIT: 100M
    networks:
      - default
      - traefik_proxy
    depends_on:
      - db
    logging:
      driver: fluentd
      options:
        tag: wedding-manuele-robine.phpmyadmin
    labels:
      traefik.enable: true

      traefik.http.routers.wedding-manuele-robine-phpmyadmin0.entrypoints: web
      traefik.http.routers.wedding-manuele-robine-phpmyadmin0.rule: Host(`phpmyadmin-wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine-phpmyadmin0.middlewares: to_https

      traefik.http.routers.wedding-manuele-robine-phpmyadmin.entrypoints: websecure
      traefik.http.routers.wedding-manuele-robine-phpmyadmin.rule: Host(`phpmyadmin-wedding-manuele-robine.d3strukt0r.dev`)
      traefik.http.routers.wedding-manuele-robine-phpmyadmin.tls: true
      traefik.http.routers.wedding-manuele-robine-phpmyadmin.tls.certresolver: le

networks:
  traefik_proxy:
    external: true
