services:
  datadoghq:
    container_name: dd-agent
    image: 'gcr.io/datadoghq/agent:7'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: datadoghq.eu
