services:
  pwa:
    image: d3strukt0r/weleda-webcenter-text-export:latest
    pull_policy: always
    init: true
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 130M
    networks:
      - default
      - traefik_proxy
    logging:
      driver: fluentd
      options:
        tag: weleda-webcenter-text-export.prod.pwa
    labels:
      traefik.enable: true

      traefik.http.routers.weleda-webcenter-text-export-prod0.entrypoints: web
      traefik.http.routers.weleda-webcenter-text-export-prod0.rule: Host(`weleda-webcenter-text-export.d3strukt0r.dev`) || Host(`webcenter-text-export.manuele-vaccari.ch`)
      traefik.http.routers.weleda-webcenter-text-export-prod0.middlewares: to_https

      traefik.http.routers.weleda-webcenter-text-export-prod.entrypoints: websecure
      traefik.http.routers.weleda-webcenter-text-export-prod.rule: Host(`weleda-webcenter-text-export.d3strukt0r.dev`) || Host(`webcenter-text-export.manuele-vaccari.ch`)
      traefik.http.routers.weleda-webcenter-text-export-prod.tls: true
      traefik.http.routers.weleda-webcenter-text-export-prod.tls.certresolver: le

networks:
  traefik_proxy:
    external: true
