services:
  mariadb:
    volumes:
      - ./database:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
  tiredofit-db-backup:
    depends_on:
      mariadb:
        condition: service_healthy
