services:
  gitea:
    image: gitea/gitea:1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    networks:
      - default
      - traefik_proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    environment:
      USER_UID: 1000
      USER_GID: 1000

      GITEA__APP_NAME: 'Gitea: D3strukt0r'
      GITEA__service__DISABLE_REGISTRATION: 'true'

      GITEA__security__SECRET_KEY: ${GITEA__security__SECRET_KEY:?GITEA__security__SECRET_KEY not set}
      GITEA__security__INTERNAL_TOKEN: ${GITEA__security__INTERNAL_TOKEN:?GITEA__security__INTERNAL_TOKEN not set}

      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: db
      GITEA__database__USER: db
      GITEA__database__PASSWD: ${DB_PASSWORD}

      #GITEA__mailer__ENABLED: true
      #GITEA__mailer__FROM: ${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
      #GITEA__mailer__PROTOCOL: smtps
      #GITEA__mailer__HOST: ${GITEA__mailer__HOST:?GITEA__mailer__HOST not set}
      #GITEA__mailer__USER: ${GITEA__mailer__USER:-apikey}
      #GITEA__mailer__PASSWD: """${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
    labels:
      traefik.enable: true
      traefik.http.services.gitea.loadbalancer.server.port: 3000
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.rule: Host(`gitea.d3strukt0r.dev`)
      traefik.http.routers.gitea.tls: true
      traefik.http.routers.gitea.tls.certresolver: le

  db:
    image: mariadb:11
    init: true
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--user=db", "--password=${DB_PASSWORD}"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 280M
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # Create "db" user with password ${DB_PASSWORD} if it doesn't exist
      MARIADB_USER: db
      MARIADB_PASSWORD: ${DB_PASSWORD}
      # Create database "db" if it doesn't exist
      MARIADB_DATABASE: db
    #logging:
    #  driver: fluentd
    #  options:
    #    tag: gitea.prod.mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    init: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    environment:
      # Default user to be logged in
      #PMA_USER: db
      #PMA_PASSWORD: ${DB_PASSWORD}
      # PhpMyAdmin User to manage PMA db
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: pma
      PMA_CONTROLPASS: ${DB_PMA_PASSWORD}
      # Other settings
      UPLOAD_LIMIT: 100M
    networks:
      - default
      - traefik_proxy
    depends_on:
      - db
    #logging:
    #  driver: fluentd
    #  options:
    #    tag: gitea.prod.phpmyadmin
    labels:
      traefik.enable: true
      traefik.http.routers.gitea-phpmyadmin.entrypoints: websecure
      traefik.http.routers.gitea-phpmyadmin.rule: Host(`phpmyadmin-gitea.d3strukt0r.dev`)
      traefik.http.routers.gitea-phpmyadmin.tls: true
      traefik.http.routers.gitea-phpmyadmin.tls.certresolver: le


networks:
  traefik_proxy:
    external: true
