include:
  - path: ../../common/mariadb.compose.yml
    env_file: .mariadb.env
  - path: ../../common/phpmyadmin.compose.yml
    env_file: .phpmyadmin.env

services:
  gitea:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    image: gitea/gitea:1
    deploy:
      resources:
        limits:
          memory: 500M
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
    networks:
      - default
      - traefik_proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      # Ensure that the authorized_keys file is shared between the host git user and the container git user
      - /home/git/.ssh/:/data/git/.ssh
    links:
      - mariadb:db
    ports:
      - '127.0.0.1:2222:22'
    environment:
      USER_UID: 1002 # Check `id -u git`
      USER_GID: 1002 # Check `id -g git`

      GITEA__APP_NAME: 'Gitea: D3strukt0r'
      GITEA__server__SSH_DOMAIN: ssh.d3strukt0r.dev
      GITEA__service__DISABLE_REGISTRATION: 'true'

      GITEA__security__SECRET_KEY: ${GITEA__security__SECRET_KEY:?GITEA__security__SECRET_KEY not set}
      GITEA__security__INTERNAL_TOKEN: ${GITEA__security__INTERNAL_TOKEN:?GITEA__security__INTERNAL_TOKEN not set}

      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: db
      GITEA__database__USER: db
      GITEA__database__PASSWD: ${DB_PASSWORD:?DB_PASSWORD not set}

      #GITEA__mailer__ENABLED: true
      #GITEA__mailer__FROM: ${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
      #GITEA__mailer__PROTOCOL: smtps
      #GITEA__mailer__HOST: ${GITEA__mailer__HOST:?GITEA__mailer__HOST not set}
      #GITEA__mailer__USER: ${GITEA__mailer__USER:-apikey}
      #GITEA__mailer__PASSWD: """${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.gitea
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
