services:
  nginx:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: nginx
    healthcheck:
      test: curl --fail http://localhost || exit 1
    networks:
      - default
      - traefik_proxy
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
