# Manage docker containers
services:
  portainer:
    extends:
      file: ../../../common/snippets.yml
      service: common-service
    image: portainer/portainer-ce:alpine
    # Normal version has not OS, so to get wget we need alpine version at least
    # https://github.com/portainer/portainer/issues/3572
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1
    deploy:
      resources:
        limits:
          memory: 100M
    networks:
      - default
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/data/
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.portainer
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9000
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
