include:
  - path: ../../common/mariadb.compose.yml
    env_file: .mariadb.env
  - path: ../../common/phpmyadmin.compose.yml
    env_file: .phpmyadmin.env
  # https://github.com/barolab/verdaccio-minio
  - path: ../../common/minio.compose.yml
    env_file: .minio.env

services:
  verdaccio:
    extends:
      file: ../../common/snippets.yml
      service: common-service
    build:
      context: .
      args:
        VERDACCIO_VERSION: 5
    deploy:
      resources:
        limits:
          memory: 140M
    #environment:
    #  S3_BUCKET: default3
    #  S3_ENDPOINT: http://${S3_SERVICE:-minio}:9000
    #  S3_ACCESS_KEY_ID: minio
    #  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY not set}
    networks:
      - default
      - traefik_proxy
    depends_on:
      - minio
      - mariadb
    links:
      - mariadb:db
    logging:
      driver: fluentd
      options:
        tag: ${COMPOSE_PROJECT_NAME}.prod.verdaccio
    volumes:
      - './config:/verdaccio/conf'
      - './storage:/verdaccio/storage'
    #environment:
    #  DATABASE_URL: mysql://db:${DB_PASSWORD}@db:3306/db # TODO: Not supported yet
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.d3strukt0r.dev`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le

networks:
  traefik_proxy:
    external: true
