# https://glitchtip.com/documentation/install#docker-compose
# https://glitchtip.com/assets/docker-compose.sample.yml

# https://glitchtip.com/documentation/install#configuration
x-environment: &default-environment
  DATABASE_URL: postgres://postgres:${DB_PASSWORD}@postgres:5432/postgres
  SECRET_KEY: ${SECRET_KEY} # best to run openssl rand -hex 32
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: https://glitchtip.d3strukt0r.dev # Change this to your domain
  DEFAULT_FROM_EMAIL: glitchtip-contact@d3st.dev # Change this to your email
  CELERY_WORKER_AUTOSCALE: "1,3"  # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"
  ENABLE_USER_REGISTRATION: "false" # Set to "false" to disable user registration

x-depends_on: &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 160M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.adminer
    networks:
      - default
      - traefik_proxy
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.entrypoints: websecure
      traefik.http.routers.adminer.rule: Host(`adminer-glitchtip.d3strukt0r.dev`)
      traefik.http.routers.adminer.tls: true
      traefik.http.routers.adminer.tls.certresolver: le
  redis:
    image: redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.redis
  web:
    image: glitchtip/glitchtip
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.web
    depends_on: *default-depends_on
    environment: *default-environment
    networks:
      - default
      - traefik_proxy
    volumes:
      - ./uploads:/code/uploads
    labels:
      traefik.enable: true
      traefik.http.routers.glitchtip.entrypoints: websecure
      traefik.http.routers.glitchtip.rule: Host(`glitchtip.d3strukt0r.dev`)
      traefik.http.routers.glitchtip.tls: true
      traefik.http.routers.glitchtip.tls.certresolver: le
  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 480M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.worker
    depends_on: *default-depends_on
    environment: *default-environment
    volumes:
      - ./uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip
    command: "./manage.py migrate"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
    logging:
      driver: fluentd
      options:
        tag: glitchtip.prod.migrate
    depends_on: *default-depends_on
    environment: *default-environment

networks:
  traefik_proxy:
    external: true
