services:
  mariadb:
    volumes:
      - ./database:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
    logging:
      options:
        # TODO: Use "${COMPOSE_PROJECT_NAME}" if we can remove "-dev" from the string
        tag: wedding-manuele-robine.dev.mariadb
  phpmyadmin:
    logging:
      options:
        # TODO: Use "${COMPOSE_PROJECT_NAME}" if we can remove "-dev" from the string
        tag: wedding-manuele-robine.dev.phpmyadmin
  minio:
    volumes:
      - ./minio:/data
    logging:
      options:
        # TODO: Use "${COMPOSE_PROJECT_NAME}" if we can remove "-dev" from the string
        tag: wedding-manuele-robine.dev.minio
